name: Build and Test

on: 
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

      steps:
      - name:  Clone the repository
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
